apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  resources:
    - name: git-py
      type: git
    - name: git-py-registry-image
      type: image

  # params:
  #   - name: pathToContext
  #     description: The path to the build context, used by Kaniko - within the workspace
  #     default: .
  #   - name: imageUrl
  #     description: Url of image repository
  #   - name: imageTag
  #     description: Tag to apply to the built image
  tasks:
  - name: source-to-image
    taskRef:
      name: source-to-image
    # params:
    #   - name: pathToContext
    #     value: "${params.pathToContext}"
    #   - name: imageUrl
    #     value: "${params.imageUrl}"
    #   - name: imageTag
    #     value: "${params.imageTag}"
    resources:
      inputs:
        - name: git-py
          resource: git-py
      outputs:
        - name: git-py-registry-image
          resource: git-py-registry-image
    