version: '3'

services:

  redis:
    image: "redis:alpine"
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379

  flask:
    depends_on:
        - redis
    build: https://github.com/eltsc/hello-redis.git
    container_name: flask
    ports:
      - 8080:8080    

volumes:
  redis:
    driver: local
