version: '3'

services:

  redis:
    build: ./redis
    container_name: redis
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379

  flask:
    depends_on:
        - redis
    build: ./web
    container_name: flask
    ports:
      - 8080:8080    

volumes:
  redis:
    driver: local
