apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    name: flask-redis-cicd
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: redis-py
        spec:
            containers:                    
                - name: redis
                  image: redis
                  ports:
                    - containerPort: 6379

                - name: flask-redis
                  image: image-registry.openshift-image-registry.svc:5000/hello-openshift-elad/py-flask:latest
                  ports:
                    - containerPort: 8080
  
