apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
    name: git-py
spec:
    type: git
    params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/eltsc/hello-redis.git