apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  resources:
  - name: py-flask-repo
    type: git
  - name: py-flask-image
    type: image
  params:
  - name: deployment-name
    description: name of the deployment to be patched
  tasks:
  - name: build-image
    taskRef:
      name: buildah-elad
    resources:
      inputs:
      - name: py-flask-repo
        resource: py-flask-repo
      outputs:
      - name: py-flask-image
        resource: py-flask-image
    params:
    - name: TLSVERIFY
      value: "false"
  - name: create-update-deployment
    taskRef:
      name: oc-apply-deployment
    resources:
      inputs:
      - name: k8s-yamls-repo
        resource: py-flask-repo
      - name: new-image
        resource: py-flask-image
    params:
    - name: deployment-name
      value: $(params.deployment-name)
    runAfter:
    - build-image